// Code generated by protoc-gen-go.
// source: ots_protocol_2.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	ots_protocol_2.proto

It has these top-level messages:
	Error
	ColumnSchema
	ColumnValue
	Column
	Row
	TableMeta
	Condition
	CapacityUnit
	ReservedThroughputDetails
	ReservedThroughput
	ConsumedCapacity
	CreateTableRequest
	CreateTableResponse
	UpdateTableRequest
	UpdateTableResponse
	DescribeTableRequest
	DescribeTableResponse
	ListTableRequest
	ListTableResponse
	DeleteTableRequest
	DeleteTableResponse
	GetRowRequest
	GetRowResponse
	ColumnUpdate
	UpdateRowRequest
	UpdateRowResponse
	PutRowRequest
	PutRowResponse
	DeleteRowRequest
	DeleteRowResponse
	RowInBatchGetRowRequest
	TableInBatchGetRowRequest
	BatchGetRowRequest
	RowInBatchGetRowResponse
	TableInBatchGetRowResponse
	BatchGetRowResponse
	PutRowInBatchWriteRowRequest
	UpdateRowInBatchWriteRowRequest
	DeleteRowInBatchWriteRowRequest
	TableInBatchWriteRowRequest
	BatchWriteRowRequest
	RowInBatchWriteRowResponse
	TableInBatchWriteRowResponse
	BatchWriteRowResponse
	GetRangeRequest
	GetRangeResponse
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ColumnType int32

const (
	ColumnType_INF_MIN ColumnType = 0
	ColumnType_INF_MAX ColumnType = 1
	ColumnType_INTEGER ColumnType = 2
	ColumnType_STRING  ColumnType = 3
	ColumnType_BOOLEAN ColumnType = 4
	ColumnType_DOUBLE  ColumnType = 5
	ColumnType_BINARY  ColumnType = 6
)

var ColumnType_name = map[int32]string{
	0: "INF_MIN",
	1: "INF_MAX",
	2: "INTEGER",
	3: "STRING",
	4: "BOOLEAN",
	5: "DOUBLE",
	6: "BINARY",
}
var ColumnType_value = map[string]int32{
	"INF_MIN": 0,
	"INF_MAX": 1,
	"INTEGER": 2,
	"STRING":  3,
	"BOOLEAN": 4,
	"DOUBLE":  5,
	"BINARY":  6,
}

func (x ColumnType) Enum() *ColumnType {
	p := new(ColumnType)
	*p = x
	return p
}
func (x ColumnType) String() string {
	return proto.EnumName(ColumnType_name, int32(x))
}
func (x *ColumnType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ColumnType_value, data, "ColumnType")
	if err != nil {
		return err
	}
	*x = ColumnType(value)
	return nil
}

type RowExistenceExpectation int32

const (
	RowExistenceExpectation_IGNORE           RowExistenceExpectation = 0
	RowExistenceExpectation_EXPECT_EXIST     RowExistenceExpectation = 1
	RowExistenceExpectation_EXPECT_NOT_EXIST RowExistenceExpectation = 2
)

var RowExistenceExpectation_name = map[int32]string{
	0: "IGNORE",
	1: "EXPECT_EXIST",
	2: "EXPECT_NOT_EXIST",
}
var RowExistenceExpectation_value = map[string]int32{
	"IGNORE":           0,
	"EXPECT_EXIST":     1,
	"EXPECT_NOT_EXIST": 2,
}

func (x RowExistenceExpectation) Enum() *RowExistenceExpectation {
	p := new(RowExistenceExpectation)
	*p = x
	return p
}
func (x RowExistenceExpectation) String() string {
	return proto.EnumName(RowExistenceExpectation_name, int32(x))
}
func (x *RowExistenceExpectation) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RowExistenceExpectation_value, data, "RowExistenceExpectation")
	if err != nil {
		return err
	}
	*x = RowExistenceExpectation(value)
	return nil
}

// UpdateRow
type OperationType int32

const (
	OperationType_PUT    OperationType = 1
	OperationType_DELETE OperationType = 2
)

var OperationType_name = map[int32]string{
	1: "PUT",
	2: "DELETE",
}
var OperationType_value = map[string]int32{
	"PUT":    1,
	"DELETE": 2,
}

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}
func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}
func (x *OperationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OperationType_value, data, "OperationType")
	if err != nil {
		return err
	}
	*x = OperationType(value)
	return nil
}

// GetRange
type Direction int32

const (
	Direction_FORWARD  Direction = 0
	Direction_BACKWARD Direction = 1
)

var Direction_name = map[int32]string{
	0: "FORWARD",
	1: "BACKWARD",
}
var Direction_value = map[string]int32{
	"FORWARD":  0,
	"BACKWARD": 1,
}

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}
func (x Direction) String() string {
	return proto.EnumName(Direction_name, int32(x))
}
func (x *Direction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Direction_value, data, "Direction")
	if err != nil {
		return err
	}
	*x = Direction(value)
	return nil
}

type Error struct {
	Code             *string `protobuf:"bytes,1,req,name=code" json:"code,omitempty"`
	Message          *string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}

func (m *Error) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type ColumnSchema struct {
	Name             *string     `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Type             *ColumnType `protobuf:"varint,2,req,name=type,enum=protobuf.ColumnType" json:"type,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ColumnSchema) Reset()         { *m = ColumnSchema{} }
func (m *ColumnSchema) String() string { return proto.CompactTextString(m) }
func (*ColumnSchema) ProtoMessage()    {}

func (m *ColumnSchema) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ColumnSchema) GetType() ColumnType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ColumnType_INF_MIN
}

type ColumnValue struct {
	Type             *ColumnType `protobuf:"varint,1,req,name=type,enum=protobuf.ColumnType" json:"type,omitempty"`
	VInt             *int64      `protobuf:"varint,2,opt,name=v_int" json:"v_int,omitempty"`
	VString          *string     `protobuf:"bytes,3,opt,name=v_string" json:"v_string,omitempty"`
	VBool            *bool       `protobuf:"varint,4,opt,name=v_bool" json:"v_bool,omitempty"`
	VDouble          *float64    `protobuf:"fixed64,5,opt,name=v_double" json:"v_double,omitempty"`
	VBinary          []byte      `protobuf:"bytes,6,opt,name=v_binary" json:"v_binary,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ColumnValue) Reset()         { *m = ColumnValue{} }
func (m *ColumnValue) String() string { return proto.CompactTextString(m) }
func (*ColumnValue) ProtoMessage()    {}

func (m *ColumnValue) GetType() ColumnType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ColumnType_INF_MIN
}

func (m *ColumnValue) GetVInt() int64 {
	if m != nil && m.VInt != nil {
		return *m.VInt
	}
	return 0
}

func (m *ColumnValue) GetVString() string {
	if m != nil && m.VString != nil {
		return *m.VString
	}
	return ""
}

func (m *ColumnValue) GetVBool() bool {
	if m != nil && m.VBool != nil {
		return *m.VBool
	}
	return false
}

func (m *ColumnValue) GetVDouble() float64 {
	if m != nil && m.VDouble != nil {
		return *m.VDouble
	}
	return 0
}

func (m *ColumnValue) GetVBinary() []byte {
	if m != nil {
		return m.VBinary
	}
	return nil
}

type Column struct {
	Name             *string      `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *ColumnValue `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Column) Reset()         { *m = Column{} }
func (m *Column) String() string { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()    {}

func (m *Column) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Column) GetValue() *ColumnValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type Row struct {
	PrimaryKeyColumns []*Column `protobuf:"bytes,1,rep,name=primary_key_columns" json:"primary_key_columns,omitempty"`
	AttributeColumns  []*Column `protobuf:"bytes,2,rep,name=attribute_columns" json:"attribute_columns,omitempty"`
	XXX_unrecognized  []byte    `json:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}

func (m *Row) GetPrimaryKeyColumns() []*Column {
	if m != nil {
		return m.PrimaryKeyColumns
	}
	return nil
}

func (m *Row) GetAttributeColumns() []*Column {
	if m != nil {
		return m.AttributeColumns
	}
	return nil
}

type TableMeta struct {
	TableName        *string         `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	PrimaryKey       []*ColumnSchema `protobuf:"bytes,2,rep,name=primary_key" json:"primary_key,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *TableMeta) Reset()         { *m = TableMeta{} }
func (m *TableMeta) String() string { return proto.CompactTextString(m) }
func (*TableMeta) ProtoMessage()    {}

func (m *TableMeta) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableMeta) GetPrimaryKey() []*ColumnSchema {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

type Condition struct {
	RowExistence     *RowExistenceExpectation `protobuf:"varint,1,req,name=row_existence,enum=protobuf.RowExistenceExpectation" json:"row_existence,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}

func (m *Condition) GetRowExistence() RowExistenceExpectation {
	if m != nil && m.RowExistence != nil {
		return *m.RowExistence
	}
	return RowExistenceExpectation_IGNORE
}

type CapacityUnit struct {
	Read             *int32 `protobuf:"varint,1,opt,name=read" json:"read,omitempty"`
	Write            *int32 `protobuf:"varint,2,opt,name=write" json:"write,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CapacityUnit) Reset()         { *m = CapacityUnit{} }
func (m *CapacityUnit) String() string { return proto.CompactTextString(m) }
func (*CapacityUnit) ProtoMessage()    {}

func (m *CapacityUnit) GetRead() int32 {
	if m != nil && m.Read != nil {
		return *m.Read
	}
	return 0
}

func (m *CapacityUnit) GetWrite() int32 {
	if m != nil && m.Write != nil {
		return *m.Write
	}
	return 0
}

type ReservedThroughputDetails struct {
	CapacityUnit           *CapacityUnit `protobuf:"bytes,1,req,name=capacity_unit" json:"capacity_unit,omitempty"`
	LastIncreaseTime       *int64        `protobuf:"varint,2,req,name=last_increase_time" json:"last_increase_time,omitempty"`
	LastDecreaseTime       *int64        `protobuf:"varint,3,opt,name=last_decrease_time" json:"last_decrease_time,omitempty"`
	NumberOfDecreasesToday *int32        `protobuf:"varint,4,req,name=number_of_decreases_today" json:"number_of_decreases_today,omitempty"`
	XXX_unrecognized       []byte        `json:"-"`
}

func (m *ReservedThroughputDetails) Reset()         { *m = ReservedThroughputDetails{} }
func (m *ReservedThroughputDetails) String() string { return proto.CompactTextString(m) }
func (*ReservedThroughputDetails) ProtoMessage()    {}

func (m *ReservedThroughputDetails) GetCapacityUnit() *CapacityUnit {
	if m != nil {
		return m.CapacityUnit
	}
	return nil
}

func (m *ReservedThroughputDetails) GetLastIncreaseTime() int64 {
	if m != nil && m.LastIncreaseTime != nil {
		return *m.LastIncreaseTime
	}
	return 0
}

func (m *ReservedThroughputDetails) GetLastDecreaseTime() int64 {
	if m != nil && m.LastDecreaseTime != nil {
		return *m.LastDecreaseTime
	}
	return 0
}

func (m *ReservedThroughputDetails) GetNumberOfDecreasesToday() int32 {
	if m != nil && m.NumberOfDecreasesToday != nil {
		return *m.NumberOfDecreasesToday
	}
	return 0
}

type ReservedThroughput struct {
	CapacityUnit     *CapacityUnit `protobuf:"bytes,1,req,name=capacity_unit" json:"capacity_unit,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ReservedThroughput) Reset()         { *m = ReservedThroughput{} }
func (m *ReservedThroughput) String() string { return proto.CompactTextString(m) }
func (*ReservedThroughput) ProtoMessage()    {}

func (m *ReservedThroughput) GetCapacityUnit() *CapacityUnit {
	if m != nil {
		return m.CapacityUnit
	}
	return nil
}

type ConsumedCapacity struct {
	CapacityUnit     *CapacityUnit `protobuf:"bytes,1,req,name=capacity_unit" json:"capacity_unit,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ConsumedCapacity) Reset()         { *m = ConsumedCapacity{} }
func (m *ConsumedCapacity) String() string { return proto.CompactTextString(m) }
func (*ConsumedCapacity) ProtoMessage()    {}

func (m *ConsumedCapacity) GetCapacityUnit() *CapacityUnit {
	if m != nil {
		return m.CapacityUnit
	}
	return nil
}

// CreateTable
type CreateTableRequest struct {
	TableMeta          *TableMeta          `protobuf:"bytes,1,req,name=table_meta" json:"table_meta,omitempty"`
	ReservedThroughput *ReservedThroughput `protobuf:"bytes,2,req,name=reserved_throughput" json:"reserved_throughput,omitempty"`
	XXX_unrecognized   []byte              `json:"-"`
}

func (m *CreateTableRequest) Reset()         { *m = CreateTableRequest{} }
func (m *CreateTableRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTableRequest) ProtoMessage()    {}

func (m *CreateTableRequest) GetTableMeta() *TableMeta {
	if m != nil {
		return m.TableMeta
	}
	return nil
}

func (m *CreateTableRequest) GetReservedThroughput() *ReservedThroughput {
	if m != nil {
		return m.ReservedThroughput
	}
	return nil
}

type CreateTableResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateTableResponse) Reset()         { *m = CreateTableResponse{} }
func (m *CreateTableResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTableResponse) ProtoMessage()    {}

type UpdateTableRequest struct {
	TableName          *string             `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	ReservedThroughput *ReservedThroughput `protobuf:"bytes,2,req,name=reserved_throughput" json:"reserved_throughput,omitempty"`
	XXX_unrecognized   []byte              `json:"-"`
}

func (m *UpdateTableRequest) Reset()         { *m = UpdateTableRequest{} }
func (m *UpdateTableRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTableRequest) ProtoMessage()    {}

func (m *UpdateTableRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *UpdateTableRequest) GetReservedThroughput() *ReservedThroughput {
	if m != nil {
		return m.ReservedThroughput
	}
	return nil
}

type UpdateTableResponse struct {
	ReservedThroughputDetails *ReservedThroughputDetails `protobuf:"bytes,1,req,name=reserved_throughput_details" json:"reserved_throughput_details,omitempty"`
	XXX_unrecognized          []byte                     `json:"-"`
}

func (m *UpdateTableResponse) Reset()         { *m = UpdateTableResponse{} }
func (m *UpdateTableResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTableResponse) ProtoMessage()    {}

func (m *UpdateTableResponse) GetReservedThroughputDetails() *ReservedThroughputDetails {
	if m != nil {
		return m.ReservedThroughputDetails
	}
	return nil
}

// DescribeTable
type DescribeTableRequest struct {
	TableName        *string `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DescribeTableRequest) Reset()         { *m = DescribeTableRequest{} }
func (m *DescribeTableRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeTableRequest) ProtoMessage()    {}

func (m *DescribeTableRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

type DescribeTableResponse struct {
	TableMeta                 *TableMeta                 `protobuf:"bytes,1,req,name=table_meta" json:"table_meta,omitempty"`
	ReservedThroughputDetails *ReservedThroughputDetails `protobuf:"bytes,2,req,name=reserved_throughput_details" json:"reserved_throughput_details,omitempty"`
	XXX_unrecognized          []byte                     `json:"-"`
}

func (m *DescribeTableResponse) Reset()         { *m = DescribeTableResponse{} }
func (m *DescribeTableResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeTableResponse) ProtoMessage()    {}

func (m *DescribeTableResponse) GetTableMeta() *TableMeta {
	if m != nil {
		return m.TableMeta
	}
	return nil
}

func (m *DescribeTableResponse) GetReservedThroughputDetails() *ReservedThroughputDetails {
	if m != nil {
		return m.ReservedThroughputDetails
	}
	return nil
}

// ListTable
type ListTableRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ListTableRequest) Reset()         { *m = ListTableRequest{} }
func (m *ListTableRequest) String() string { return proto.CompactTextString(m) }
func (*ListTableRequest) ProtoMessage()    {}

type ListTableResponse struct {
	TableNames       []string `protobuf:"bytes,1,rep,name=table_names" json:"table_names,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ListTableResponse) Reset()         { *m = ListTableResponse{} }
func (m *ListTableResponse) String() string { return proto.CompactTextString(m) }
func (*ListTableResponse) ProtoMessage()    {}

func (m *ListTableResponse) GetTableNames() []string {
	if m != nil {
		return m.TableNames
	}
	return nil
}

// DeleteTable
type DeleteTableRequest struct {
	TableName        *string `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteTableRequest) Reset()         { *m = DeleteTableRequest{} }
func (m *DeleteTableRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTableRequest) ProtoMessage()    {}

func (m *DeleteTableRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

type DeleteTableResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteTableResponse) Reset()         { *m = DeleteTableResponse{} }
func (m *DeleteTableResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTableResponse) ProtoMessage()    {}

// GetRow
type GetRowRequest struct {
	TableName        *string   `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	PrimaryKey       []*Column `protobuf:"bytes,2,rep,name=primary_key" json:"primary_key,omitempty"`
	ColumnsToGet     []string  `protobuf:"bytes,3,rep,name=columns_to_get" json:"columns_to_get,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *GetRowRequest) Reset()         { *m = GetRowRequest{} }
func (m *GetRowRequest) String() string { return proto.CompactTextString(m) }
func (*GetRowRequest) ProtoMessage()    {}

func (m *GetRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *GetRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

func (m *GetRowRequest) GetColumnsToGet() []string {
	if m != nil {
		return m.ColumnsToGet
	}
	return nil
}

type GetRowResponse struct {
	Consumed         *ConsumedCapacity `protobuf:"bytes,1,req,name=consumed" json:"consumed,omitempty"`
	Row              *Row              `protobuf:"bytes,2,req,name=row" json:"row,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *GetRowResponse) Reset()         { *m = GetRowResponse{} }
func (m *GetRowResponse) String() string { return proto.CompactTextString(m) }
func (*GetRowResponse) ProtoMessage()    {}

func (m *GetRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

func (m *GetRowResponse) GetRow() *Row {
	if m != nil {
		return m.Row
	}
	return nil
}

type ColumnUpdate struct {
	Type             *OperationType `protobuf:"varint,1,req,name=type,enum=protobuf.OperationType" json:"type,omitempty"`
	Name             *string        `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Value            *ColumnValue   `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ColumnUpdate) Reset()         { *m = ColumnUpdate{} }
func (m *ColumnUpdate) String() string { return proto.CompactTextString(m) }
func (*ColumnUpdate) ProtoMessage()    {}

func (m *ColumnUpdate) GetType() OperationType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return OperationType_PUT
}

func (m *ColumnUpdate) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ColumnUpdate) GetValue() *ColumnValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type UpdateRowRequest struct {
	TableName        *string         `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Condition        *Condition      `protobuf:"bytes,2,req,name=condition" json:"condition,omitempty"`
	PrimaryKey       []*Column       `protobuf:"bytes,3,rep,name=primary_key" json:"primary_key,omitempty"`
	AttributeColumns []*ColumnUpdate `protobuf:"bytes,4,rep,name=attribute_columns" json:"attribute_columns,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *UpdateRowRequest) Reset()         { *m = UpdateRowRequest{} }
func (m *UpdateRowRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRowRequest) ProtoMessage()    {}

func (m *UpdateRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *UpdateRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *UpdateRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

func (m *UpdateRowRequest) GetAttributeColumns() []*ColumnUpdate {
	if m != nil {
		return m.AttributeColumns
	}
	return nil
}

type UpdateRowResponse struct {
	Consumed         *ConsumedCapacity `protobuf:"bytes,1,req,name=consumed" json:"consumed,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *UpdateRowResponse) Reset()         { *m = UpdateRowResponse{} }
func (m *UpdateRowResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRowResponse) ProtoMessage()    {}

func (m *UpdateRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

// PutRow
type PutRowRequest struct {
	TableName        *string    `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Condition        *Condition `protobuf:"bytes,2,req,name=condition" json:"condition,omitempty"`
	PrimaryKey       []*Column  `protobuf:"bytes,3,rep,name=primary_key" json:"primary_key,omitempty"`
	AttributeColumns []*Column  `protobuf:"bytes,4,rep,name=attribute_columns" json:"attribute_columns,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *PutRowRequest) Reset()         { *m = PutRowRequest{} }
func (m *PutRowRequest) String() string { return proto.CompactTextString(m) }
func (*PutRowRequest) ProtoMessage()    {}

func (m *PutRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *PutRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *PutRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

func (m *PutRowRequest) GetAttributeColumns() []*Column {
	if m != nil {
		return m.AttributeColumns
	}
	return nil
}

type PutRowResponse struct {
	Consumed         *ConsumedCapacity `protobuf:"bytes,1,req,name=consumed" json:"consumed,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PutRowResponse) Reset()         { *m = PutRowResponse{} }
func (m *PutRowResponse) String() string { return proto.CompactTextString(m) }
func (*PutRowResponse) ProtoMessage()    {}

func (m *PutRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

// DeleteRow
type DeleteRowRequest struct {
	TableName        *string    `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Condition        *Condition `protobuf:"bytes,2,req,name=condition" json:"condition,omitempty"`
	PrimaryKey       []*Column  `protobuf:"bytes,3,rep,name=primary_key" json:"primary_key,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *DeleteRowRequest) Reset()         { *m = DeleteRowRequest{} }
func (m *DeleteRowRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRowRequest) ProtoMessage()    {}

func (m *DeleteRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *DeleteRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *DeleteRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

type DeleteRowResponse struct {
	Consumed         *ConsumedCapacity `protobuf:"bytes,1,req,name=consumed" json:"consumed,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *DeleteRowResponse) Reset()         { *m = DeleteRowResponse{} }
func (m *DeleteRowResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRowResponse) ProtoMessage()    {}

func (m *DeleteRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

// BatchGetRow
type RowInBatchGetRowRequest struct {
	PrimaryKey       []*Column `protobuf:"bytes,1,rep,name=primary_key" json:"primary_key,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *RowInBatchGetRowRequest) Reset()         { *m = RowInBatchGetRowRequest{} }
func (m *RowInBatchGetRowRequest) String() string { return proto.CompactTextString(m) }
func (*RowInBatchGetRowRequest) ProtoMessage()    {}

func (m *RowInBatchGetRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

type TableInBatchGetRowRequest struct {
	TableName        *string                    `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Rows             []*RowInBatchGetRowRequest `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
	ColumnsToGet     []string                   `protobuf:"bytes,3,rep,name=columns_to_get" json:"columns_to_get,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *TableInBatchGetRowRequest) Reset()         { *m = TableInBatchGetRowRequest{} }
func (m *TableInBatchGetRowRequest) String() string { return proto.CompactTextString(m) }
func (*TableInBatchGetRowRequest) ProtoMessage()    {}

func (m *TableInBatchGetRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableInBatchGetRowRequest) GetRows() []*RowInBatchGetRowRequest {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *TableInBatchGetRowRequest) GetColumnsToGet() []string {
	if m != nil {
		return m.ColumnsToGet
	}
	return nil
}

type BatchGetRowRequest struct {
	Tables           []*TableInBatchGetRowRequest `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *BatchGetRowRequest) Reset()         { *m = BatchGetRowRequest{} }
func (m *BatchGetRowRequest) String() string { return proto.CompactTextString(m) }
func (*BatchGetRowRequest) ProtoMessage()    {}

func (m *BatchGetRowRequest) GetTables() []*TableInBatchGetRowRequest {
	if m != nil {
		return m.Tables
	}
	return nil
}

type RowInBatchGetRowResponse struct {
	IsOk             *bool             `protobuf:"varint,1,req,name=is_ok,def=1" json:"is_ok,omitempty"`
	Error            *Error            `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Consumed         *ConsumedCapacity `protobuf:"bytes,3,opt,name=consumed" json:"consumed,omitempty"`
	Row              *Row              `protobuf:"bytes,4,opt,name=row" json:"row,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RowInBatchGetRowResponse) Reset()         { *m = RowInBatchGetRowResponse{} }
func (m *RowInBatchGetRowResponse) String() string { return proto.CompactTextString(m) }
func (*RowInBatchGetRowResponse) ProtoMessage()    {}

const Default_RowInBatchGetRowResponse_IsOk bool = true

func (m *RowInBatchGetRowResponse) GetIsOk() bool {
	if m != nil && m.IsOk != nil {
		return *m.IsOk
	}
	return Default_RowInBatchGetRowResponse_IsOk
}

func (m *RowInBatchGetRowResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *RowInBatchGetRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

func (m *RowInBatchGetRowResponse) GetRow() *Row {
	if m != nil {
		return m.Row
	}
	return nil
}

type TableInBatchGetRowResponse struct {
	TableName        *string                     `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Rows             []*RowInBatchGetRowResponse `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *TableInBatchGetRowResponse) Reset()         { *m = TableInBatchGetRowResponse{} }
func (m *TableInBatchGetRowResponse) String() string { return proto.CompactTextString(m) }
func (*TableInBatchGetRowResponse) ProtoMessage()    {}

func (m *TableInBatchGetRowResponse) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableInBatchGetRowResponse) GetRows() []*RowInBatchGetRowResponse {
	if m != nil {
		return m.Rows
	}
	return nil
}

type BatchGetRowResponse struct {
	Tables           []*TableInBatchGetRowResponse `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *BatchGetRowResponse) Reset()         { *m = BatchGetRowResponse{} }
func (m *BatchGetRowResponse) String() string { return proto.CompactTextString(m) }
func (*BatchGetRowResponse) ProtoMessage()    {}

func (m *BatchGetRowResponse) GetTables() []*TableInBatchGetRowResponse {
	if m != nil {
		return m.Tables
	}
	return nil
}

// BatchWriteRow
type PutRowInBatchWriteRowRequest struct {
	Condition        *Condition `protobuf:"bytes,1,req,name=condition" json:"condition,omitempty"`
	PrimaryKey       []*Column  `protobuf:"bytes,2,rep,name=primary_key" json:"primary_key,omitempty"`
	AttributeColumns []*Column  `protobuf:"bytes,3,rep,name=attribute_columns" json:"attribute_columns,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *PutRowInBatchWriteRowRequest) Reset()         { *m = PutRowInBatchWriteRowRequest{} }
func (m *PutRowInBatchWriteRowRequest) String() string { return proto.CompactTextString(m) }
func (*PutRowInBatchWriteRowRequest) ProtoMessage()    {}

func (m *PutRowInBatchWriteRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *PutRowInBatchWriteRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

func (m *PutRowInBatchWriteRowRequest) GetAttributeColumns() []*Column {
	if m != nil {
		return m.AttributeColumns
	}
	return nil
}

type UpdateRowInBatchWriteRowRequest struct {
	Condition        *Condition      `protobuf:"bytes,1,req,name=condition" json:"condition,omitempty"`
	PrimaryKey       []*Column       `protobuf:"bytes,2,rep,name=primary_key" json:"primary_key,omitempty"`
	AttributeColumns []*ColumnUpdate `protobuf:"bytes,3,rep,name=attribute_columns" json:"attribute_columns,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *UpdateRowInBatchWriteRowRequest) Reset()         { *m = UpdateRowInBatchWriteRowRequest{} }
func (m *UpdateRowInBatchWriteRowRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRowInBatchWriteRowRequest) ProtoMessage()    {}

func (m *UpdateRowInBatchWriteRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *UpdateRowInBatchWriteRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

func (m *UpdateRowInBatchWriteRowRequest) GetAttributeColumns() []*ColumnUpdate {
	if m != nil {
		return m.AttributeColumns
	}
	return nil
}

type DeleteRowInBatchWriteRowRequest struct {
	Condition        *Condition `protobuf:"bytes,1,req,name=condition" json:"condition,omitempty"`
	PrimaryKey       []*Column  `protobuf:"bytes,2,rep,name=primary_key" json:"primary_key,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *DeleteRowInBatchWriteRowRequest) Reset()         { *m = DeleteRowInBatchWriteRowRequest{} }
func (m *DeleteRowInBatchWriteRowRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRowInBatchWriteRowRequest) ProtoMessage()    {}

func (m *DeleteRowInBatchWriteRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *DeleteRowInBatchWriteRowRequest) GetPrimaryKey() []*Column {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

type TableInBatchWriteRowRequest struct {
	TableName        *string                            `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	PutRows          []*PutRowInBatchWriteRowRequest    `protobuf:"bytes,2,rep,name=put_rows" json:"put_rows,omitempty"`
	UpdateRows       []*UpdateRowInBatchWriteRowRequest `protobuf:"bytes,3,rep,name=update_rows" json:"update_rows,omitempty"`
	DeleteRows       []*DeleteRowInBatchWriteRowRequest `protobuf:"bytes,4,rep,name=delete_rows" json:"delete_rows,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *TableInBatchWriteRowRequest) Reset()         { *m = TableInBatchWriteRowRequest{} }
func (m *TableInBatchWriteRowRequest) String() string { return proto.CompactTextString(m) }
func (*TableInBatchWriteRowRequest) ProtoMessage()    {}

func (m *TableInBatchWriteRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableInBatchWriteRowRequest) GetPutRows() []*PutRowInBatchWriteRowRequest {
	if m != nil {
		return m.PutRows
	}
	return nil
}

func (m *TableInBatchWriteRowRequest) GetUpdateRows() []*UpdateRowInBatchWriteRowRequest {
	if m != nil {
		return m.UpdateRows
	}
	return nil
}

func (m *TableInBatchWriteRowRequest) GetDeleteRows() []*DeleteRowInBatchWriteRowRequest {
	if m != nil {
		return m.DeleteRows
	}
	return nil
}

type BatchWriteRowRequest struct {
	Tables           []*TableInBatchWriteRowRequest `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *BatchWriteRowRequest) Reset()         { *m = BatchWriteRowRequest{} }
func (m *BatchWriteRowRequest) String() string { return proto.CompactTextString(m) }
func (*BatchWriteRowRequest) ProtoMessage()    {}

func (m *BatchWriteRowRequest) GetTables() []*TableInBatchWriteRowRequest {
	if m != nil {
		return m.Tables
	}
	return nil
}

type RowInBatchWriteRowResponse struct {
	IsOk             *bool             `protobuf:"varint,1,req,name=is_ok,def=1" json:"is_ok,omitempty"`
	Error            *Error            `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Consumed         *ConsumedCapacity `protobuf:"bytes,3,opt,name=consumed" json:"consumed,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RowInBatchWriteRowResponse) Reset()         { *m = RowInBatchWriteRowResponse{} }
func (m *RowInBatchWriteRowResponse) String() string { return proto.CompactTextString(m) }
func (*RowInBatchWriteRowResponse) ProtoMessage()    {}

const Default_RowInBatchWriteRowResponse_IsOk bool = true

func (m *RowInBatchWriteRowResponse) GetIsOk() bool {
	if m != nil && m.IsOk != nil {
		return *m.IsOk
	}
	return Default_RowInBatchWriteRowResponse_IsOk
}

func (m *RowInBatchWriteRowResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *RowInBatchWriteRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

type TableInBatchWriteRowResponse struct {
	TableName        *string                       `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	PutRows          []*RowInBatchWriteRowResponse `protobuf:"bytes,2,rep,name=put_rows" json:"put_rows,omitempty"`
	UpdateRows       []*RowInBatchWriteRowResponse `protobuf:"bytes,3,rep,name=update_rows" json:"update_rows,omitempty"`
	DeleteRows       []*RowInBatchWriteRowResponse `protobuf:"bytes,4,rep,name=delete_rows" json:"delete_rows,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *TableInBatchWriteRowResponse) Reset()         { *m = TableInBatchWriteRowResponse{} }
func (m *TableInBatchWriteRowResponse) String() string { return proto.CompactTextString(m) }
func (*TableInBatchWriteRowResponse) ProtoMessage()    {}

func (m *TableInBatchWriteRowResponse) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableInBatchWriteRowResponse) GetPutRows() []*RowInBatchWriteRowResponse {
	if m != nil {
		return m.PutRows
	}
	return nil
}

func (m *TableInBatchWriteRowResponse) GetUpdateRows() []*RowInBatchWriteRowResponse {
	if m != nil {
		return m.UpdateRows
	}
	return nil
}

func (m *TableInBatchWriteRowResponse) GetDeleteRows() []*RowInBatchWriteRowResponse {
	if m != nil {
		return m.DeleteRows
	}
	return nil
}

type BatchWriteRowResponse struct {
	Tables           []*TableInBatchWriteRowResponse `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *BatchWriteRowResponse) Reset()         { *m = BatchWriteRowResponse{} }
func (m *BatchWriteRowResponse) String() string { return proto.CompactTextString(m) }
func (*BatchWriteRowResponse) ProtoMessage()    {}

func (m *BatchWriteRowResponse) GetTables() []*TableInBatchWriteRowResponse {
	if m != nil {
		return m.Tables
	}
	return nil
}

type GetRangeRequest struct {
	TableName                *string    `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Direction                *Direction `protobuf:"varint,2,req,name=direction,enum=protobuf.Direction" json:"direction,omitempty"`
	ColumnsToGet             []string   `protobuf:"bytes,3,rep,name=columns_to_get" json:"columns_to_get,omitempty"`
	Limit                    *int32     `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
	InclusiveStartPrimaryKey []*Column  `protobuf:"bytes,5,rep,name=inclusive_start_primary_key" json:"inclusive_start_primary_key,omitempty"`
	ExclusiveEndPrimaryKey   []*Column  `protobuf:"bytes,6,rep,name=exclusive_end_primary_key" json:"exclusive_end_primary_key,omitempty"`
	XXX_unrecognized         []byte     `json:"-"`
}

func (m *GetRangeRequest) Reset()         { *m = GetRangeRequest{} }
func (m *GetRangeRequest) String() string { return proto.CompactTextString(m) }
func (*GetRangeRequest) ProtoMessage()    {}

func (m *GetRangeRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *GetRangeRequest) GetDirection() Direction {
	if m != nil && m.Direction != nil {
		return *m.Direction
	}
	return Direction_FORWARD
}

func (m *GetRangeRequest) GetColumnsToGet() []string {
	if m != nil {
		return m.ColumnsToGet
	}
	return nil
}

func (m *GetRangeRequest) GetLimit() int32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

func (m *GetRangeRequest) GetInclusiveStartPrimaryKey() []*Column {
	if m != nil {
		return m.InclusiveStartPrimaryKey
	}
	return nil
}

func (m *GetRangeRequest) GetExclusiveEndPrimaryKey() []*Column {
	if m != nil {
		return m.ExclusiveEndPrimaryKey
	}
	return nil
}

type GetRangeResponse struct {
	Consumed            *ConsumedCapacity `protobuf:"bytes,1,req,name=consumed" json:"consumed,omitempty"`
	NextStartPrimaryKey []*Column         `protobuf:"bytes,2,rep,name=next_start_primary_key" json:"next_start_primary_key,omitempty"`
	Rows                []*Row            `protobuf:"bytes,3,rep,name=rows" json:"rows,omitempty"`
	XXX_unrecognized    []byte            `json:"-"`
}

func (m *GetRangeResponse) Reset()         { *m = GetRangeResponse{} }
func (m *GetRangeResponse) String() string { return proto.CompactTextString(m) }
func (*GetRangeResponse) ProtoMessage()    {}

func (m *GetRangeResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

func (m *GetRangeResponse) GetNextStartPrimaryKey() []*Column {
	if m != nil {
		return m.NextStartPrimaryKey
	}
	return nil
}

func (m *GetRangeResponse) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterEnum("protobuf.ColumnType", ColumnType_name, ColumnType_value)
	proto.RegisterEnum("protobuf.RowExistenceExpectation", RowExistenceExpectation_name, RowExistenceExpectation_value)
	proto.RegisterEnum("protobuf.OperationType", OperationType_name, OperationType_value)
	proto.RegisterEnum("protobuf.Direction", Direction_name, Direction_value)
}
